import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

/**
 * ESLint, flat config.
 *
 * Two jobs, deliberately kept apart in the blocks below:
 *
 * 1. **Find bugs.** `react-hooks` is the reason this file exists — a stale
 *    dependency array in a debounced autosave is the class of bug that reaches
 *    production silently, and `tsc` cannot see it.
 * 2. **Enforce the conventions in `CLAUDE.md`.** Every rule under "repo
 *    conventions" is one a reviewer used to have to catch by eye. The message
 *    on each says what to do instead, so the failure teaches the rule.
 *
 * Formatting is **not** this file's job: `eslint-config-prettier` is applied
 * last and switches off every stylistic rule, so Prettier owns layout and
 * ESLint never argues with it.
 *
 * Type-aware linting (`recommendedTypeChecked` — `no-floating-promises` and
 * friends) is deliberately not on: it needs the TS program on every run, and
 * the existing violations have not been triaged. It is the obvious next step.
 */
/**
 * CLAUDE.md: z-index comes from `config/zIndex.ts` as an inline style, so the
 * stacking order of the whole app is readable in one file instead of scattered
 * across arbitrary-value classes.
 */
const NO_Z_CLASSES = [
  {
    selector:
      'JSXAttribute[name.name="className"] Literal[value=/(^|\\s)z-\\[/]',
    message:
      'Apply z-index from config/zIndex.ts via inline style={{ zIndex }}, not a z-[…] class.',
  },
  {
    selector:
      'JSXAttribute[name.name="className"] TemplateElement[value.raw=/(^|\\s)z-\\[/]',
    message:
      'Apply z-index from config/zIndex.ts via inline style={{ zIndex }}, not a z-[…] class.',
  },
]

/**
 * CLAUDE.md + docs/colors.md: colours only through semantic tokens, never a raw
 * palette step. A literal white is the common slip.
 */
const NO_RAW_COLOURS = [
  {
    selector:
      'JSXAttribute[name.name="className"] Literal[value=/(^|\\s)(bg|text|border|ring|fill|stroke|divide|outline)-(white|black)(\\s|$|\\/)/]',
    message:
      'Use a semantic colour token (bg-primary, text-tertiary-foreground …), not bg-white/text-black. See docs/colors.md.',
  },
  {
    selector:
      'JSXAttribute[name.name="className"] TemplateElement[value.raw=/(^|\\s)(bg|text|border|ring|fill|stroke|divide|outline)-(white|black)(\\s|$|\\/)/]',
    message:
      'Use a semantic colour token (bg-primary, text-tertiary-foreground …), not bg-white/text-black. See docs/colors.md.',
  },
]

export default tseslint.config(
  {
    ignores: [
      // Generated by the TanStack Router plugin. CLAUDE.md: never hand-edit.
      'src/routeTree.gen.ts',
      'dist',
      'coverage',
      '.tanstack',
      // Untracked per-worktree dev overlay — never committed, so never linted.
      'vite.config.js',
      // Design harnesses are fixtures on their own `design/*` branches and
      // never reach `develop`; linting them would fail builds over code CI
      // cannot see. See CLAUDE.md.
      'src/routes/design/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ---------------------------------------------------------------- app code
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,

      // `rules-of-hooks` and `exhaustive-deps` stay errors: they are at zero,
      // and they are the two that catch the stale-closure class of bug.
      //
      // The rest of what `react-hooks` v7 ships are the React Compiler rules,
      // and they are **warnings on purpose**. They report on code that predates
      // them — 29 `set-state-in-effect`, 28 `refs`, 5 `purity`, 4 skipped
      // compilations — and every one of those is a judgement call about a
      // component's behaviour, not a mechanical fix. Made errors today they
      // would only teach people to reach for `eslint-disable`. Triage them in
      // their own pass, promote them as each category reaches zero, and delete
      // this block when the last one does.
      'react-hooks/exhaustive-deps': 'error',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/incompatible-library': 'warn',

      // Vite's fast refresh only works when a module exports components and
      // nothing else. `allowConstantExport` covers the `const x = …` pattern
      // route files use.
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],

      // `tsc` already refuses unused locals and parameters (tsconfig
      // `noUnusedLocals`/`noUnusedParameters`); this keeps `_`-prefixed
      // arguments deliberately exempt in both tools.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'no-var': 'error',
      // `console.warn`/`error` are developer-facing and allowed (CLAUDE.md
      // exempts them from the i18n rule too); a stray `console.log` is debris.
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    },
  },

  // -------------------------------------------------------- repo conventions
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': ['error', ...NO_Z_CLASSES, ...NO_RAW_COLOURS],
    },
  },

  {
    // The post previews are the one place a literal white or black is right:
    // they draw *the platform's* chrome — YouTube's duration pill, a Story's
    // caption over its image — and that chrome is not ours to re-theme. A
    // semantic token there would make the preview lie about what publishing
    // actually looks like. Exempt from the colour rule, and from nothing else:
    // the z-index rule is repeated here because a flat-config block replaces a
    // rule's options rather than merging with them.
    files: ['src/components/posts/preview/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': ['error', ...NO_Z_CLASSES],
    },
  },

  {
    // CLAUDE.md: every request carries the tab's workspace as `X-Workspace-Id`.
    // A bare `fetch` skips that header and lands in whichever workspace the
    // account happens to default to — the one bug per-request scoping exists to
    // prevent. `services/api/` is where the wrappers live, so it is exempt.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/services/api/**'],
    rules: {
      'no-restricted-globals': [
        'error',
        {
          name: 'fetch',
          message:
            'Call the API through services/api/ (apiJson/apiVoid, or scopedFetch) so the request carries X-Workspace-Id.',
        },
      ],
    },
  },

  // ------------------------------------------------------------------- tests
  {
    files: ['src/**/*.test.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    rules: {
      // A test may talk to a bare `fetch` it has stubbed itself, and may say
      // so on the console. `no-explicit-any` stays **on**: the one place that
      // needs it already carries a disable explaining why, and that is the
      // form an escape hatch should take.
      'no-restricted-globals': 'off',
      'no-console': 'off',
    },
  },

  // ------------------------------------------------------------ config files
  {
    files: ['*.config.{ts,js}', 'vite.config.ts'],
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      'no-console': 'off',
      // `/// <reference types="vitest/config" />` is how vitest's config types
      // reach a vite config; there is no import form of it.
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },

  // Last, so it wins: Prettier owns formatting.
  prettier,
)
