/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ServerUnavailableIndexRouteImport } from './routes/server-unavailable/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContentBankRouteImport } from './routes/_authenticated/content-bank'
import { Route as DesignAnalyticsIndexRouteImport } from './routes/design/analytics/index'
import { Route as AuthResetIndexRouteImport } from './routes/auth/reset/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLogoutIndexRouteImport } from './routes/auth/logout/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthForgotIndexRouteImport } from './routes/auth/forgot/index'
import { Route as AuthenticatedWorkspaceSettingsIndexRouteImport } from './routes/_authenticated/workspace-settings/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedContentBankIndexRouteImport } from './routes/_authenticated/content-bank/index'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns/index'
import { Route as AuthenticatedContentBankAssetIdRouteImport } from './routes/_authenticated/content-bank_/$assetId'
import { Route as AuthenticatedContentBankTextRouteImport } from './routes/_authenticated/content-bank/text'
import { Route as AuthenticatedContentBankImageryRouteImport } from './routes/_authenticated/content-bank/imagery'
import { Route as AuthenticatedContentBankFilesRouteImport } from './routes/_authenticated/content-bank/files'
import { Route as AuthenticatedContentBankAllRouteImport } from './routes/_authenticated/content-bank/all'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns/$campaignId'
import { Route as DesignAnalyticsWidgetsIndexRouteImport } from './routes/design/analytics/widgets/index'
import { Route as DesignAnalyticsPostIndexRouteImport } from './routes/design/analytics/post/index'
import { Route as DesignAnalyticsCampaignIndexRouteImport } from './routes/design/analytics/campaign/index'
import { Route as AuthenticatedCampaignsCampaignIdIndexRouteImport } from './routes/_authenticated/campaigns/$campaignId/index'
import { Route as AuthenticatedCampaignsCampaignIdSettingsRouteImport } from './routes/_authenticated/campaigns/$campaignId/settings'
import { Route as AuthenticatedCampaignsCampaignIdOverviewRouteImport } from './routes/_authenticated/campaigns/$campaignId/overview'
import { Route as AuthenticatedCampaignsCampaignIdListRouteImport } from './routes/_authenticated/campaigns/$campaignId/list'
import { Route as AuthenticatedCampaignsCampaignIdBriefRouteImport } from './routes/_authenticated/campaigns/$campaignId/brief'
import { Route as AuthenticatedCampaignsCampaignIdAssetsRouteImport } from './routes/_authenticated/campaigns/$campaignId/assets'
import { Route as AuthenticatedCampaignsCampaignIdAnalyticsRouteImport } from './routes/_authenticated/campaigns/$campaignId/analytics'
import { Route as DesignAnalyticsWidgetsQualityIndexRouteImport } from './routes/design/analytics/widgets/quality/index'
import { Route as DesignAnalyticsWidgetsPostIndexRouteImport } from './routes/design/analytics/widgets/post/index'
import { Route as DesignAnalyticsWidgetsPlatformFilterIndexRouteImport } from './routes/design/analytics/widgets/platform-filter/index'
import { Route as DesignAnalyticsWidgetsPerformersIndexRouteImport } from './routes/design/analytics/widgets/performers/index'
import { Route as DesignAnalyticsWidgetsDailyEngagementRateIndexRouteImport } from './routes/design/analytics/widgets/daily-engagement-rate/index'
import { Route as DesignAnalyticsWidgetsCurrentFollowersIndexRouteImport } from './routes/design/analytics/widgets/current-followers/index'
import { Route as DesignAnalyticsWidgetsCumulativeReachIndexRouteImport } from './routes/design/analytics/widgets/cumulative-reach/index'
import { Route as DesignAnalyticsWidgetsCumulativeInteractionsIndexRouteImport } from './routes/design/analytics/widgets/cumulative-interactions/index'
import { Route as AuthenticatedCampaignsCampaignIdCalendarIndexRouteImport } from './routes/_authenticated/campaigns/$campaignId/calendar/index'
import { Route as AuthenticatedCampaignsCampaignIdPostsPostIdRouteImport } from './routes/_authenticated/campaigns/$campaignId_/posts/$postId'
import { Route as DesignAnalyticsWidgetsPostOverviewIndexRouteImport } from './routes/design/analytics/widgets/post/overview/index'
import { Route as DesignAnalyticsWidgetsPostIdentityIndexRouteImport } from './routes/design/analytics/widgets/post/identity/index'
import { Route as DesignAnalyticsWidgetsPostMeasureIndexRouteImport } from './routes/design/analytics/widgets/post/$measure/index'
import { Route as AuthenticatedCampaignsCampaignIdCalendarAnchorViewRouteImport } from './routes/_authenticated/campaigns/$campaignId/calendar/$anchor/$view'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerUnavailableIndexRoute = ServerUnavailableIndexRouteImport.update({
  id: '/server-unavailable/',
  path: '/server-unavailable/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentBankRoute =
  AuthenticatedContentBankRouteImport.update({
    id: '/content-bank',
    path: '/content-bank',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DesignAnalyticsIndexRoute = DesignAnalyticsIndexRouteImport.update({
  id: '/design/analytics/',
  path: '/design/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetIndexRoute = AuthResetIndexRouteImport.update({
  id: '/auth/reset/',
  path: '/auth/reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutIndexRoute = AuthLogoutIndexRouteImport.update({
  id: '/auth/logout/',
  path: '/auth/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotIndexRoute = AuthForgotIndexRouteImport.update({
  id: '/auth/forgot/',
  path: '/auth/forgot/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceSettingsIndexRoute =
  AuthenticatedWorkspaceSettingsIndexRouteImport.update({
    id: '/workspace-settings/',
    path: '/workspace-settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentBankIndexRoute =
  AuthenticatedContentBankIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContentBankRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentBankAssetIdRoute =
  AuthenticatedContentBankAssetIdRouteImport.update({
    id: '/content-bank_/$assetId',
    path: '/content-bank/$assetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentBankTextRoute =
  AuthenticatedContentBankTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => AuthenticatedContentBankRoute,
  } as any)
const AuthenticatedContentBankImageryRoute =
  AuthenticatedContentBankImageryRouteImport.update({
    id: '/imagery',
    path: '/imagery',
    getParentRoute: () => AuthenticatedContentBankRoute,
  } as any)
const AuthenticatedContentBankFilesRoute =
  AuthenticatedContentBankFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedContentBankRoute,
  } as any)
const AuthenticatedContentBankAllRoute =
  AuthenticatedContentBankAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => AuthenticatedContentBankRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DesignAnalyticsWidgetsIndexRoute =
  DesignAnalyticsWidgetsIndexRouteImport.update({
    id: '/design/analytics/widgets/',
    path: '/design/analytics/widgets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsPostIndexRoute =
  DesignAnalyticsPostIndexRouteImport.update({
    id: '/design/analytics/post/',
    path: '/design/analytics/post/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsCampaignIndexRoute =
  DesignAnalyticsCampaignIndexRouteImport.update({
    id: '/design/analytics/campaign/',
    path: '/design/analytics/campaign/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCampaignsCampaignIdIndexRoute =
  AuthenticatedCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdSettingsRoute =
  AuthenticatedCampaignsCampaignIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdOverviewRoute =
  AuthenticatedCampaignsCampaignIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdListRoute =
  AuthenticatedCampaignsCampaignIdListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdBriefRoute =
  AuthenticatedCampaignsCampaignIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdAssetsRoute =
  AuthenticatedCampaignsCampaignIdAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdAnalyticsRoute =
  AuthenticatedCampaignsCampaignIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const DesignAnalyticsWidgetsQualityIndexRoute =
  DesignAnalyticsWidgetsQualityIndexRouteImport.update({
    id: '/design/analytics/widgets/quality/',
    path: '/design/analytics/widgets/quality/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsPostIndexRoute =
  DesignAnalyticsWidgetsPostIndexRouteImport.update({
    id: '/design/analytics/widgets/post/',
    path: '/design/analytics/widgets/post/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsPlatformFilterIndexRoute =
  DesignAnalyticsWidgetsPlatformFilterIndexRouteImport.update({
    id: '/design/analytics/widgets/platform-filter/',
    path: '/design/analytics/widgets/platform-filter/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsPerformersIndexRoute =
  DesignAnalyticsWidgetsPerformersIndexRouteImport.update({
    id: '/design/analytics/widgets/performers/',
    path: '/design/analytics/widgets/performers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsDailyEngagementRateIndexRoute =
  DesignAnalyticsWidgetsDailyEngagementRateIndexRouteImport.update({
    id: '/design/analytics/widgets/daily-engagement-rate/',
    path: '/design/analytics/widgets/daily-engagement-rate/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsCurrentFollowersIndexRoute =
  DesignAnalyticsWidgetsCurrentFollowersIndexRouteImport.update({
    id: '/design/analytics/widgets/current-followers/',
    path: '/design/analytics/widgets/current-followers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsCumulativeReachIndexRoute =
  DesignAnalyticsWidgetsCumulativeReachIndexRouteImport.update({
    id: '/design/analytics/widgets/cumulative-reach/',
    path: '/design/analytics/widgets/cumulative-reach/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute =
  DesignAnalyticsWidgetsCumulativeInteractionsIndexRouteImport.update({
    id: '/design/analytics/widgets/cumulative-interactions/',
    path: '/design/analytics/widgets/cumulative-interactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCampaignsCampaignIdCalendarIndexRoute =
  AuthenticatedCampaignsCampaignIdCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdPostsPostIdRoute =
  AuthenticatedCampaignsCampaignIdPostsPostIdRouteImport.update({
    id: '/campaigns/$campaignId_/posts/$postId',
    path: '/campaigns/$campaignId/posts/$postId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DesignAnalyticsWidgetsPostOverviewIndexRoute =
  DesignAnalyticsWidgetsPostOverviewIndexRouteImport.update({
    id: '/design/analytics/widgets/post/overview/',
    path: '/design/analytics/widgets/post/overview/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsPostIdentityIndexRoute =
  DesignAnalyticsWidgetsPostIdentityIndexRouteImport.update({
    id: '/design/analytics/widgets/post/identity/',
    path: '/design/analytics/widgets/post/identity/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DesignAnalyticsWidgetsPostMeasureIndexRoute =
  DesignAnalyticsWidgetsPostMeasureIndexRouteImport.update({
    id: '/design/analytics/widgets/post/$measure/',
    path: '/design/analytics/widgets/post/$measure/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute =
  AuthenticatedCampaignsCampaignIdCalendarAnchorViewRouteImport.update({
    id: '/calendar/$anchor/$view',
    path: '/calendar/$anchor/$view',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/content-bank': typeof AuthenticatedContentBankRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/server-unavailable/': typeof ServerUnavailableIndexRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/content-bank/all': typeof AuthenticatedContentBankAllRoute
  '/content-bank/files': typeof AuthenticatedContentBankFilesRoute
  '/content-bank/imagery': typeof AuthenticatedContentBankImageryRoute
  '/content-bank/text': typeof AuthenticatedContentBankTextRoute
  '/content-bank/$assetId': typeof AuthenticatedContentBankAssetIdRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/content-bank/': typeof AuthenticatedContentBankIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/workspace-settings/': typeof AuthenticatedWorkspaceSettingsIndexRoute
  '/auth/forgot/': typeof AuthForgotIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset/': typeof AuthResetIndexRoute
  '/design/analytics/': typeof DesignAnalyticsIndexRoute
  '/campaigns/$campaignId/analytics': typeof AuthenticatedCampaignsCampaignIdAnalyticsRoute
  '/campaigns/$campaignId/assets': typeof AuthenticatedCampaignsCampaignIdAssetsRoute
  '/campaigns/$campaignId/brief': typeof AuthenticatedCampaignsCampaignIdBriefRoute
  '/campaigns/$campaignId/list': typeof AuthenticatedCampaignsCampaignIdListRoute
  '/campaigns/$campaignId/overview': typeof AuthenticatedCampaignsCampaignIdOverviewRoute
  '/campaigns/$campaignId/settings': typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  '/campaigns/$campaignId/': typeof AuthenticatedCampaignsCampaignIdIndexRoute
  '/design/analytics/campaign/': typeof DesignAnalyticsCampaignIndexRoute
  '/design/analytics/post/': typeof DesignAnalyticsPostIndexRoute
  '/design/analytics/widgets/': typeof DesignAnalyticsWidgetsIndexRoute
  '/campaigns/$campaignId/posts/$postId': typeof AuthenticatedCampaignsCampaignIdPostsPostIdRoute
  '/campaigns/$campaignId/calendar/': typeof AuthenticatedCampaignsCampaignIdCalendarIndexRoute
  '/design/analytics/widgets/cumulative-interactions/': typeof DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute
  '/design/analytics/widgets/cumulative-reach/': typeof DesignAnalyticsWidgetsCumulativeReachIndexRoute
  '/design/analytics/widgets/current-followers/': typeof DesignAnalyticsWidgetsCurrentFollowersIndexRoute
  '/design/analytics/widgets/daily-engagement-rate/': typeof DesignAnalyticsWidgetsDailyEngagementRateIndexRoute
  '/design/analytics/widgets/performers/': typeof DesignAnalyticsWidgetsPerformersIndexRoute
  '/design/analytics/widgets/platform-filter/': typeof DesignAnalyticsWidgetsPlatformFilterIndexRoute
  '/design/analytics/widgets/post/': typeof DesignAnalyticsWidgetsPostIndexRoute
  '/design/analytics/widgets/quality/': typeof DesignAnalyticsWidgetsQualityIndexRoute
  '/campaigns/$campaignId/calendar/$anchor/$view': typeof AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute
  '/design/analytics/widgets/post/$measure/': typeof DesignAnalyticsWidgetsPostMeasureIndexRoute
  '/design/analytics/widgets/post/identity/': typeof DesignAnalyticsWidgetsPostIdentityIndexRoute
  '/design/analytics/widgets/post/overview/': typeof DesignAnalyticsWidgetsPostOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/server-unavailable': typeof ServerUnavailableIndexRoute
  '/content-bank/all': typeof AuthenticatedContentBankAllRoute
  '/content-bank/files': typeof AuthenticatedContentBankFilesRoute
  '/content-bank/imagery': typeof AuthenticatedContentBankImageryRoute
  '/content-bank/text': typeof AuthenticatedContentBankTextRoute
  '/content-bank/$assetId': typeof AuthenticatedContentBankAssetIdRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/content-bank': typeof AuthenticatedContentBankIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/workspace-settings': typeof AuthenticatedWorkspaceSettingsIndexRoute
  '/auth/forgot': typeof AuthForgotIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/logout': typeof AuthLogoutIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset': typeof AuthResetIndexRoute
  '/design/analytics': typeof DesignAnalyticsIndexRoute
  '/campaigns/$campaignId/analytics': typeof AuthenticatedCampaignsCampaignIdAnalyticsRoute
  '/campaigns/$campaignId/assets': typeof AuthenticatedCampaignsCampaignIdAssetsRoute
  '/campaigns/$campaignId/brief': typeof AuthenticatedCampaignsCampaignIdBriefRoute
  '/campaigns/$campaignId/list': typeof AuthenticatedCampaignsCampaignIdListRoute
  '/campaigns/$campaignId/overview': typeof AuthenticatedCampaignsCampaignIdOverviewRoute
  '/campaigns/$campaignId/settings': typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdIndexRoute
  '/design/analytics/campaign': typeof DesignAnalyticsCampaignIndexRoute
  '/design/analytics/post': typeof DesignAnalyticsPostIndexRoute
  '/design/analytics/widgets': typeof DesignAnalyticsWidgetsIndexRoute
  '/campaigns/$campaignId/posts/$postId': typeof AuthenticatedCampaignsCampaignIdPostsPostIdRoute
  '/campaigns/$campaignId/calendar': typeof AuthenticatedCampaignsCampaignIdCalendarIndexRoute
  '/design/analytics/widgets/cumulative-interactions': typeof DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute
  '/design/analytics/widgets/cumulative-reach': typeof DesignAnalyticsWidgetsCumulativeReachIndexRoute
  '/design/analytics/widgets/current-followers': typeof DesignAnalyticsWidgetsCurrentFollowersIndexRoute
  '/design/analytics/widgets/daily-engagement-rate': typeof DesignAnalyticsWidgetsDailyEngagementRateIndexRoute
  '/design/analytics/widgets/performers': typeof DesignAnalyticsWidgetsPerformersIndexRoute
  '/design/analytics/widgets/platform-filter': typeof DesignAnalyticsWidgetsPlatformFilterIndexRoute
  '/design/analytics/widgets/post': typeof DesignAnalyticsWidgetsPostIndexRoute
  '/design/analytics/widgets/quality': typeof DesignAnalyticsWidgetsQualityIndexRoute
  '/campaigns/$campaignId/calendar/$anchor/$view': typeof AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute
  '/design/analytics/widgets/post/$measure': typeof DesignAnalyticsWidgetsPostMeasureIndexRoute
  '/design/analytics/widgets/post/identity': typeof DesignAnalyticsWidgetsPostIdentityIndexRoute
  '/design/analytics/widgets/post/overview': typeof DesignAnalyticsWidgetsPostOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/content-bank': typeof AuthenticatedContentBankRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/server-unavailable/': typeof ServerUnavailableIndexRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/_authenticated/content-bank/all': typeof AuthenticatedContentBankAllRoute
  '/_authenticated/content-bank/files': typeof AuthenticatedContentBankFilesRoute
  '/_authenticated/content-bank/imagery': typeof AuthenticatedContentBankImageryRoute
  '/_authenticated/content-bank/text': typeof AuthenticatedContentBankTextRoute
  '/_authenticated/content-bank_/$assetId': typeof AuthenticatedContentBankAssetIdRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/content-bank/': typeof AuthenticatedContentBankIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/workspace-settings/': typeof AuthenticatedWorkspaceSettingsIndexRoute
  '/auth/forgot/': typeof AuthForgotIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/logout/': typeof AuthLogoutIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset/': typeof AuthResetIndexRoute
  '/design/analytics/': typeof DesignAnalyticsIndexRoute
  '/_authenticated/campaigns/$campaignId/analytics': typeof AuthenticatedCampaignsCampaignIdAnalyticsRoute
  '/_authenticated/campaigns/$campaignId/assets': typeof AuthenticatedCampaignsCampaignIdAssetsRoute
  '/_authenticated/campaigns/$campaignId/brief': typeof AuthenticatedCampaignsCampaignIdBriefRoute
  '/_authenticated/campaigns/$campaignId/list': typeof AuthenticatedCampaignsCampaignIdListRoute
  '/_authenticated/campaigns/$campaignId/overview': typeof AuthenticatedCampaignsCampaignIdOverviewRoute
  '/_authenticated/campaigns/$campaignId/settings': typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  '/_authenticated/campaigns/$campaignId/': typeof AuthenticatedCampaignsCampaignIdIndexRoute
  '/design/analytics/campaign/': typeof DesignAnalyticsCampaignIndexRoute
  '/design/analytics/post/': typeof DesignAnalyticsPostIndexRoute
  '/design/analytics/widgets/': typeof DesignAnalyticsWidgetsIndexRoute
  '/_authenticated/campaigns/$campaignId_/posts/$postId': typeof AuthenticatedCampaignsCampaignIdPostsPostIdRoute
  '/_authenticated/campaigns/$campaignId/calendar/': typeof AuthenticatedCampaignsCampaignIdCalendarIndexRoute
  '/design/analytics/widgets/cumulative-interactions/': typeof DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute
  '/design/analytics/widgets/cumulative-reach/': typeof DesignAnalyticsWidgetsCumulativeReachIndexRoute
  '/design/analytics/widgets/current-followers/': typeof DesignAnalyticsWidgetsCurrentFollowersIndexRoute
  '/design/analytics/widgets/daily-engagement-rate/': typeof DesignAnalyticsWidgetsDailyEngagementRateIndexRoute
  '/design/analytics/widgets/performers/': typeof DesignAnalyticsWidgetsPerformersIndexRoute
  '/design/analytics/widgets/platform-filter/': typeof DesignAnalyticsWidgetsPlatformFilterIndexRoute
  '/design/analytics/widgets/post/': typeof DesignAnalyticsWidgetsPostIndexRoute
  '/design/analytics/widgets/quality/': typeof DesignAnalyticsWidgetsQualityIndexRoute
  '/_authenticated/campaigns/$campaignId/calendar/$anchor/$view': typeof AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute
  '/design/analytics/widgets/post/$measure/': typeof DesignAnalyticsWidgetsPostMeasureIndexRoute
  '/design/analytics/widgets/post/identity/': typeof DesignAnalyticsWidgetsPostIdentityIndexRoute
  '/design/analytics/widgets/post/overview/': typeof DesignAnalyticsWidgetsPostOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content-bank'
    | '/auth/'
    | '/server-unavailable/'
    | '/campaigns/$campaignId'
    | '/content-bank/all'
    | '/content-bank/files'
    | '/content-bank/imagery'
    | '/content-bank/text'
    | '/content-bank/$assetId'
    | '/campaigns/'
    | '/content-bank/'
    | '/profile/'
    | '/workspace-settings/'
    | '/auth/forgot/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/auth/register/'
    | '/auth/reset/'
    | '/design/analytics/'
    | '/campaigns/$campaignId/analytics'
    | '/campaigns/$campaignId/assets'
    | '/campaigns/$campaignId/brief'
    | '/campaigns/$campaignId/list'
    | '/campaigns/$campaignId/overview'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId/'
    | '/design/analytics/campaign/'
    | '/design/analytics/post/'
    | '/design/analytics/widgets/'
    | '/campaigns/$campaignId/posts/$postId'
    | '/campaigns/$campaignId/calendar/'
    | '/design/analytics/widgets/cumulative-interactions/'
    | '/design/analytics/widgets/cumulative-reach/'
    | '/design/analytics/widgets/current-followers/'
    | '/design/analytics/widgets/daily-engagement-rate/'
    | '/design/analytics/widgets/performers/'
    | '/design/analytics/widgets/platform-filter/'
    | '/design/analytics/widgets/post/'
    | '/design/analytics/widgets/quality/'
    | '/campaigns/$campaignId/calendar/$anchor/$view'
    | '/design/analytics/widgets/post/$measure/'
    | '/design/analytics/widgets/post/identity/'
    | '/design/analytics/widgets/post/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/server-unavailable'
    | '/content-bank/all'
    | '/content-bank/files'
    | '/content-bank/imagery'
    | '/content-bank/text'
    | '/content-bank/$assetId'
    | '/campaigns'
    | '/content-bank'
    | '/profile'
    | '/workspace-settings'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset'
    | '/design/analytics'
    | '/campaigns/$campaignId/analytics'
    | '/campaigns/$campaignId/assets'
    | '/campaigns/$campaignId/brief'
    | '/campaigns/$campaignId/list'
    | '/campaigns/$campaignId/overview'
    | '/campaigns/$campaignId/settings'
    | '/campaigns/$campaignId'
    | '/design/analytics/campaign'
    | '/design/analytics/post'
    | '/design/analytics/widgets'
    | '/campaigns/$campaignId/posts/$postId'
    | '/campaigns/$campaignId/calendar'
    | '/design/analytics/widgets/cumulative-interactions'
    | '/design/analytics/widgets/cumulative-reach'
    | '/design/analytics/widgets/current-followers'
    | '/design/analytics/widgets/daily-engagement-rate'
    | '/design/analytics/widgets/performers'
    | '/design/analytics/widgets/platform-filter'
    | '/design/analytics/widgets/post'
    | '/design/analytics/widgets/quality'
    | '/campaigns/$campaignId/calendar/$anchor/$view'
    | '/design/analytics/widgets/post/$measure'
    | '/design/analytics/widgets/post/identity'
    | '/design/analytics/widgets/post/overview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/content-bank'
    | '/_authenticated/'
    | '/auth/'
    | '/server-unavailable/'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/content-bank/all'
    | '/_authenticated/content-bank/files'
    | '/_authenticated/content-bank/imagery'
    | '/_authenticated/content-bank/text'
    | '/_authenticated/content-bank_/$assetId'
    | '/_authenticated/campaigns/'
    | '/_authenticated/content-bank/'
    | '/_authenticated/profile/'
    | '/_authenticated/workspace-settings/'
    | '/auth/forgot/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/auth/register/'
    | '/auth/reset/'
    | '/design/analytics/'
    | '/_authenticated/campaigns/$campaignId/analytics'
    | '/_authenticated/campaigns/$campaignId/assets'
    | '/_authenticated/campaigns/$campaignId/brief'
    | '/_authenticated/campaigns/$campaignId/list'
    | '/_authenticated/campaigns/$campaignId/overview'
    | '/_authenticated/campaigns/$campaignId/settings'
    | '/_authenticated/campaigns/$campaignId/'
    | '/design/analytics/campaign/'
    | '/design/analytics/post/'
    | '/design/analytics/widgets/'
    | '/_authenticated/campaigns/$campaignId_/posts/$postId'
    | '/_authenticated/campaigns/$campaignId/calendar/'
    | '/design/analytics/widgets/cumulative-interactions/'
    | '/design/analytics/widgets/cumulative-reach/'
    | '/design/analytics/widgets/current-followers/'
    | '/design/analytics/widgets/daily-engagement-rate/'
    | '/design/analytics/widgets/performers/'
    | '/design/analytics/widgets/platform-filter/'
    | '/design/analytics/widgets/post/'
    | '/design/analytics/widgets/quality/'
    | '/_authenticated/campaigns/$campaignId/calendar/$anchor/$view'
    | '/design/analytics/widgets/post/$measure/'
    | '/design/analytics/widgets/post/identity/'
    | '/design/analytics/widgets/post/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ServerUnavailableIndexRoute: typeof ServerUnavailableIndexRoute
  AuthForgotIndexRoute: typeof AuthForgotIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLogoutIndexRoute: typeof AuthLogoutIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetIndexRoute: typeof AuthResetIndexRoute
  DesignAnalyticsIndexRoute: typeof DesignAnalyticsIndexRoute
  DesignAnalyticsCampaignIndexRoute: typeof DesignAnalyticsCampaignIndexRoute
  DesignAnalyticsPostIndexRoute: typeof DesignAnalyticsPostIndexRoute
  DesignAnalyticsWidgetsIndexRoute: typeof DesignAnalyticsWidgetsIndexRoute
  DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute: typeof DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute
  DesignAnalyticsWidgetsCumulativeReachIndexRoute: typeof DesignAnalyticsWidgetsCumulativeReachIndexRoute
  DesignAnalyticsWidgetsCurrentFollowersIndexRoute: typeof DesignAnalyticsWidgetsCurrentFollowersIndexRoute
  DesignAnalyticsWidgetsDailyEngagementRateIndexRoute: typeof DesignAnalyticsWidgetsDailyEngagementRateIndexRoute
  DesignAnalyticsWidgetsPerformersIndexRoute: typeof DesignAnalyticsWidgetsPerformersIndexRoute
  DesignAnalyticsWidgetsPlatformFilterIndexRoute: typeof DesignAnalyticsWidgetsPlatformFilterIndexRoute
  DesignAnalyticsWidgetsPostIndexRoute: typeof DesignAnalyticsWidgetsPostIndexRoute
  DesignAnalyticsWidgetsQualityIndexRoute: typeof DesignAnalyticsWidgetsQualityIndexRoute
  DesignAnalyticsWidgetsPostMeasureIndexRoute: typeof DesignAnalyticsWidgetsPostMeasureIndexRoute
  DesignAnalyticsWidgetsPostIdentityIndexRoute: typeof DesignAnalyticsWidgetsPostIdentityIndexRoute
  DesignAnalyticsWidgetsPostOverviewIndexRoute: typeof DesignAnalyticsWidgetsPostOverviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-unavailable/': {
      id: '/server-unavailable/'
      path: '/server-unavailable'
      fullPath: '/server-unavailable/'
      preLoaderRoute: typeof ServerUnavailableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-bank': {
      id: '/_authenticated/content-bank'
      path: '/content-bank'
      fullPath: '/content-bank'
      preLoaderRoute: typeof AuthenticatedContentBankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/design/analytics/': {
      id: '/design/analytics/'
      path: '/design/analytics'
      fullPath: '/design/analytics/'
      preLoaderRoute: typeof DesignAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset/': {
      id: '/auth/reset/'
      path: '/auth/reset'
      fullPath: '/auth/reset/'
      preLoaderRoute: typeof AuthResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout/': {
      id: '/auth/logout/'
      path: '/auth/logout'
      fullPath: '/auth/logout/'
      preLoaderRoute: typeof AuthLogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot/': {
      id: '/auth/forgot/'
      path: '/auth/forgot'
      fullPath: '/auth/forgot/'
      preLoaderRoute: typeof AuthForgotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace-settings/': {
      id: '/_authenticated/workspace-settings/'
      path: '/workspace-settings'
      fullPath: '/workspace-settings/'
      preLoaderRoute: typeof AuthenticatedWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-bank/': {
      id: '/_authenticated/content-bank/'
      path: '/'
      fullPath: '/content-bank/'
      preLoaderRoute: typeof AuthenticatedContentBankIndexRouteImport
      parentRoute: typeof AuthenticatedContentBankRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-bank_/$assetId': {
      id: '/_authenticated/content-bank_/$assetId'
      path: '/content-bank/$assetId'
      fullPath: '/content-bank/$assetId'
      preLoaderRoute: typeof AuthenticatedContentBankAssetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-bank/text': {
      id: '/_authenticated/content-bank/text'
      path: '/text'
      fullPath: '/content-bank/text'
      preLoaderRoute: typeof AuthenticatedContentBankTextRouteImport
      parentRoute: typeof AuthenticatedContentBankRoute
    }
    '/_authenticated/content-bank/imagery': {
      id: '/_authenticated/content-bank/imagery'
      path: '/imagery'
      fullPath: '/content-bank/imagery'
      preLoaderRoute: typeof AuthenticatedContentBankImageryRouteImport
      parentRoute: typeof AuthenticatedContentBankRoute
    }
    '/_authenticated/content-bank/files': {
      id: '/_authenticated/content-bank/files'
      path: '/files'
      fullPath: '/content-bank/files'
      preLoaderRoute: typeof AuthenticatedContentBankFilesRouteImport
      parentRoute: typeof AuthenticatedContentBankRoute
    }
    '/_authenticated/content-bank/all': {
      id: '/_authenticated/content-bank/all'
      path: '/all'
      fullPath: '/content-bank/all'
      preLoaderRoute: typeof AuthenticatedContentBankAllRouteImport
      parentRoute: typeof AuthenticatedContentBankRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/design/analytics/widgets/': {
      id: '/design/analytics/widgets/'
      path: '/design/analytics/widgets'
      fullPath: '/design/analytics/widgets/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/post/': {
      id: '/design/analytics/post/'
      path: '/design/analytics/post'
      fullPath: '/design/analytics/post/'
      preLoaderRoute: typeof DesignAnalyticsPostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/campaign/': {
      id: '/design/analytics/campaign/'
      path: '/design/analytics/campaign'
      fullPath: '/design/analytics/campaign/'
      preLoaderRoute: typeof DesignAnalyticsCampaignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$campaignId/': {
      id: '/_authenticated/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/settings': {
      id: '/_authenticated/campaigns/$campaignId/settings'
      path: '/settings'
      fullPath: '/campaigns/$campaignId/settings'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/overview': {
      id: '/_authenticated/campaigns/$campaignId/overview'
      path: '/overview'
      fullPath: '/campaigns/$campaignId/overview'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdOverviewRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/list': {
      id: '/_authenticated/campaigns/$campaignId/list'
      path: '/list'
      fullPath: '/campaigns/$campaignId/list'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdListRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/brief': {
      id: '/_authenticated/campaigns/$campaignId/brief'
      path: '/brief'
      fullPath: '/campaigns/$campaignId/brief'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdBriefRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/assets': {
      id: '/_authenticated/campaigns/$campaignId/assets'
      path: '/assets'
      fullPath: '/campaigns/$campaignId/assets'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdAssetsRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/analytics': {
      id: '/_authenticated/campaigns/$campaignId/analytics'
      path: '/analytics'
      fullPath: '/campaigns/$campaignId/analytics'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/design/analytics/widgets/quality/': {
      id: '/design/analytics/widgets/quality/'
      path: '/design/analytics/widgets/quality'
      fullPath: '/design/analytics/widgets/quality/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsQualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/post/': {
      id: '/design/analytics/widgets/post/'
      path: '/design/analytics/widgets/post'
      fullPath: '/design/analytics/widgets/post/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsPostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/platform-filter/': {
      id: '/design/analytics/widgets/platform-filter/'
      path: '/design/analytics/widgets/platform-filter'
      fullPath: '/design/analytics/widgets/platform-filter/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsPlatformFilterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/performers/': {
      id: '/design/analytics/widgets/performers/'
      path: '/design/analytics/widgets/performers'
      fullPath: '/design/analytics/widgets/performers/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsPerformersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/daily-engagement-rate/': {
      id: '/design/analytics/widgets/daily-engagement-rate/'
      path: '/design/analytics/widgets/daily-engagement-rate'
      fullPath: '/design/analytics/widgets/daily-engagement-rate/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsDailyEngagementRateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/current-followers/': {
      id: '/design/analytics/widgets/current-followers/'
      path: '/design/analytics/widgets/current-followers'
      fullPath: '/design/analytics/widgets/current-followers/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsCurrentFollowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/cumulative-reach/': {
      id: '/design/analytics/widgets/cumulative-reach/'
      path: '/design/analytics/widgets/cumulative-reach'
      fullPath: '/design/analytics/widgets/cumulative-reach/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsCumulativeReachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/cumulative-interactions/': {
      id: '/design/analytics/widgets/cumulative-interactions/'
      path: '/design/analytics/widgets/cumulative-interactions'
      fullPath: '/design/analytics/widgets/cumulative-interactions/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsCumulativeInteractionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$campaignId/calendar/': {
      id: '/_authenticated/campaigns/$campaignId/calendar/'
      path: '/calendar'
      fullPath: '/campaigns/$campaignId/calendar/'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId_/posts/$postId': {
      id: '/_authenticated/campaigns/$campaignId_/posts/$postId'
      path: '/campaigns/$campaignId/posts/$postId'
      fullPath: '/campaigns/$campaignId/posts/$postId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/design/analytics/widgets/post/overview/': {
      id: '/design/analytics/widgets/post/overview/'
      path: '/design/analytics/widgets/post/overview'
      fullPath: '/design/analytics/widgets/post/overview/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsPostOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/post/identity/': {
      id: '/design/analytics/widgets/post/identity/'
      path: '/design/analytics/widgets/post/identity'
      fullPath: '/design/analytics/widgets/post/identity/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsPostIdentityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/analytics/widgets/post/$measure/': {
      id: '/design/analytics/widgets/post/$measure/'
      path: '/design/analytics/widgets/post/$measure'
      fullPath: '/design/analytics/widgets/post/$measure/'
      preLoaderRoute: typeof DesignAnalyticsWidgetsPostMeasureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$campaignId/calendar/$anchor/$view': {
      id: '/_authenticated/campaigns/$campaignId/calendar/$anchor/$view'
      path: '/calendar/$anchor/$view'
      fullPath: '/campaigns/$campaignId/calendar/$anchor/$view'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdCalendarAnchorViewRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
  }
}

interface AuthenticatedContentBankRouteChildren {
  AuthenticatedContentBankAllRoute: typeof AuthenticatedContentBankAllRoute
  AuthenticatedContentBankFilesRoute: typeof AuthenticatedContentBankFilesRoute
  AuthenticatedContentBankImageryRoute: typeof AuthenticatedContentBankImageryRoute
  AuthenticatedContentBankTextRoute: typeof AuthenticatedContentBankTextRoute
  AuthenticatedContentBankIndexRoute: typeof AuthenticatedContentBankIndexRoute
}

const AuthenticatedContentBankRouteChildren: AuthenticatedContentBankRouteChildren =
  {
    AuthenticatedContentBankAllRoute: AuthenticatedContentBankAllRoute,
    AuthenticatedContentBankFilesRoute: AuthenticatedContentBankFilesRoute,
    AuthenticatedContentBankImageryRoute: AuthenticatedContentBankImageryRoute,
    AuthenticatedContentBankTextRoute: AuthenticatedContentBankTextRoute,
    AuthenticatedContentBankIndexRoute: AuthenticatedContentBankIndexRoute,
  }

const AuthenticatedContentBankRouteWithChildren =
  AuthenticatedContentBankRoute._addFileChildren(
    AuthenticatedContentBankRouteChildren,
  )

interface AuthenticatedCampaignsCampaignIdRouteChildren {
  AuthenticatedCampaignsCampaignIdAnalyticsRoute: typeof AuthenticatedCampaignsCampaignIdAnalyticsRoute
  AuthenticatedCampaignsCampaignIdAssetsRoute: typeof AuthenticatedCampaignsCampaignIdAssetsRoute
  AuthenticatedCampaignsCampaignIdBriefRoute: typeof AuthenticatedCampaignsCampaignIdBriefRoute
  AuthenticatedCampaignsCampaignIdListRoute: typeof AuthenticatedCampaignsCampaignIdListRoute
  AuthenticatedCampaignsCampaignIdOverviewRoute: typeof AuthenticatedCampaignsCampaignIdOverviewRoute
  AuthenticatedCampaignsCampaignIdSettingsRoute: typeof AuthenticatedCampaignsCampaignIdSettingsRoute
  AuthenticatedCampaignsCampaignIdIndexRoute: typeof AuthenticatedCampaignsCampaignIdIndexRoute
  AuthenticatedCampaignsCampaignIdCalendarIndexRoute: typeof AuthenticatedCampaignsCampaignIdCalendarIndexRoute
  AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute: typeof AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute
}

const AuthenticatedCampaignsCampaignIdRouteChildren: AuthenticatedCampaignsCampaignIdRouteChildren =
  {
    AuthenticatedCampaignsCampaignIdAnalyticsRoute:
      AuthenticatedCampaignsCampaignIdAnalyticsRoute,
    AuthenticatedCampaignsCampaignIdAssetsRoute:
      AuthenticatedCampaignsCampaignIdAssetsRoute,
    AuthenticatedCampaignsCampaignIdBriefRoute:
      AuthenticatedCampaignsCampaignIdBriefRoute,
    AuthenticatedCampaignsCampaignIdListRoute:
      AuthenticatedCampaignsCampaignIdListRoute,
    AuthenticatedCampaignsCampaignIdOverviewRoute:
      AuthenticatedCampaignsCampaignIdOverviewRoute,
    AuthenticatedCampaignsCampaignIdSettingsRoute:
      AuthenticatedCampaignsCampaignIdSettingsRoute,
    AuthenticatedCampaignsCampaignIdIndexRoute:
      AuthenticatedCampaignsCampaignIdIndexRoute,
    AuthenticatedCampaignsCampaignIdCalendarIndexRoute:
      AuthenticatedCampaignsCampaignIdCalendarIndexRoute,
    AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute:
      AuthenticatedCampaignsCampaignIdCalendarAnchorViewRoute,
  }

const AuthenticatedCampaignsCampaignIdRouteWithChildren =
  AuthenticatedCampaignsCampaignIdRoute._addFileChildren(
    AuthenticatedCampaignsCampaignIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedContentBankRoute: typeof AuthenticatedContentBankRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  AuthenticatedContentBankAssetIdRoute: typeof AuthenticatedContentBankAssetIdRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedWorkspaceSettingsIndexRoute: typeof AuthenticatedWorkspaceSettingsIndexRoute
  AuthenticatedCampaignsCampaignIdPostsPostIdRoute: typeof AuthenticatedCampaignsCampaignIdPostsPostIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContentBankRoute: AuthenticatedContentBankRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCampaignsCampaignIdRoute:
    AuthenticatedCampaignsCampaignIdRouteWithChildren,
  AuthenticatedContentBankAssetIdRoute: AuthenticatedContentBankAssetIdRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedWorkspaceSettingsIndexRoute:
    AuthenticatedWorkspaceSettingsIndexRoute,
  AuthenticatedCampaignsCampaignIdPostsPostIdRoute:
    AuthenticatedCampaignsCampaignIdPostsPostIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ServerUnavailableIndexRoute: ServerUnavailableIndexRoute,
  AuthForgotIndexRoute: AuthForgotIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLogoutIndexRoute: AuthLogoutIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetIndexRoute: AuthResetIndexRoute,
  DesignAnalyticsIndexRoute: DesignAnalyticsIndexRoute,
  DesignAnalyticsCampaignIndexRoute: DesignAnalyticsCampaignIndexRoute,
  DesignAnalyticsPostIndexRoute: DesignAnalyticsPostIndexRoute,
  DesignAnalyticsWidgetsIndexRoute: DesignAnalyticsWidgetsIndexRoute,
  DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute:
    DesignAnalyticsWidgetsCumulativeInteractionsIndexRoute,
  DesignAnalyticsWidgetsCumulativeReachIndexRoute:
    DesignAnalyticsWidgetsCumulativeReachIndexRoute,
  DesignAnalyticsWidgetsCurrentFollowersIndexRoute:
    DesignAnalyticsWidgetsCurrentFollowersIndexRoute,
  DesignAnalyticsWidgetsDailyEngagementRateIndexRoute:
    DesignAnalyticsWidgetsDailyEngagementRateIndexRoute,
  DesignAnalyticsWidgetsPerformersIndexRoute:
    DesignAnalyticsWidgetsPerformersIndexRoute,
  DesignAnalyticsWidgetsPlatformFilterIndexRoute:
    DesignAnalyticsWidgetsPlatformFilterIndexRoute,
  DesignAnalyticsWidgetsPostIndexRoute: DesignAnalyticsWidgetsPostIndexRoute,
  DesignAnalyticsWidgetsQualityIndexRoute:
    DesignAnalyticsWidgetsQualityIndexRoute,
  DesignAnalyticsWidgetsPostMeasureIndexRoute:
    DesignAnalyticsWidgetsPostMeasureIndexRoute,
  DesignAnalyticsWidgetsPostIdentityIndexRoute:
    DesignAnalyticsWidgetsPostIdentityIndexRoute,
  DesignAnalyticsWidgetsPostOverviewIndexRoute:
    DesignAnalyticsWidgetsPostOverviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
